// DO NOT EDIT THIS FILE MANUALLY
// YOU MUST UPDATE CONSTRAINTS IN problem.toml

#pragma once

const long long int MIN_T = 1;
const long long int MAX_T = 200000;
const long long int MIN_A = -1000000000;
const long long int MAX_A = 1000000000;
const long long int MIN_B = -1000000000;
const long long int MAX_B = 1000000000;
const long long int MIN_C = -1000000000;
const long long int MAX_C = 1000000000;
const long long int MIN_X = -2000000000;
const long long int MAX_X = 2000000000;
