// DO NOT EDIT THIS FILE MANUALLY
// YOU MUST UPDATE CONSTRAINTS IN problem.toml

#pragma once

const long long int MIN_N = 1;
const long long int MAX_N = 200000;
const long long int MIN_A = 1;
const long long int MAX_A = 1000000000;