// DO NOT EDIT THIS FILE MANUALLY
// YOU MUST UPDATE CONSTRAINTS IN problem.toml

#pragma once

const long long int MIN_T = 1;
const long long int MAX_T = 100000;
const long long int MIN_A = 0;
const long long int MAX_A = 1000000000;
