// DO NOT EDIT THIS FILE MANUALLY
// YOU MUST UPDATE CONSTRAINTS IN problem.toml

#pragma once

const long long int MIN_N = 1;
const long long int MAX_N = 150000;
const long long int MIN_A = 1;
const long long int MAX_A = 1000000000;
const long long int MIN_Q = 1;
const long long int MAX_Q = 70000;
const long long int MIN_X = 1;
const long long int MAX_X = 1000000000;
