// DO NOT EDIT THIS FILE MANUALLY
// YOU MUST UPDATE CONSTRAINTS IN problem.toml

#pragma once

const long long int MIN_X = 0;
const long long int MAX_X = 1000000000;
const long long int MIN_Y = 0;
const long long int MAX_Y = 1000000000;
const long long int MIN_W = 1;
const long long int MAX_W = 1000000000;
const long long int MIN_N = 1;
const long long int MAX_N = 100000;
const long long int MIN_Q = 1;
const long long int MAX_Q = 100000;
